Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
